### ISSUE TITLE
AttributeError: module 'SigProfilerTopography.Topography' has no attribute 'install_nucleosome'

### ISSUE THREAD

**Issue by pengbo233** [AlexandrovLab/SigProfilerTopography#1]

**Comment by burcakotlu** [comment]
Dear pengbo233,

Thanks for your interest in SigProflerTopography.
Topography.py has **install_nucleosom**e method.
Which SigProfilerTopography version are you using?

Following the sample commands in Readme.md  should work.
$ python
>> from SigProfilerTopography import Topography as topography
>> topography.install_nucleosome('GRCh37')
>> topography.install_atac_seq('GRCh37')
>> topography.install_repli_seq('GRCh37')

Let me know if you have any problems.

Best wishes,
Burcak

**Comment by burcakotlu** [comment]
Dear pengbo233,

I'm closing this issue.

After installing the latest version of SigProfilerTopography, if you are still having problems please let me know.

Best wishes,
Burcak
