### ISSUE TITLE
SigProfilerTopography runs in aggregated mutations mode even if sbs_probabilities were provided

### ISSUE THREAD

**Issue by jlevatic** [AlexandrovLab/SigProfilerTopography#2]
Dear developers, 

I am running SigProfilerTopography and despite providing sbs_probabilities it runs in the aggregated mutations mode, i.e., the figures for the individual signatures are not created. As an input, I am providing folder with .txt files (the input folder created by SigProfilerExtractor) and the De_Novo_MutationType_Probabilities.txt file as sbs_probabilities.

Would you have a suggestion what could be the problem? I exhausted my options of verifying the correctness of the input files. 

Best regards,
Jurica

**Comment by burcakotlu** [comment]
Dear Jurica,

Thanks for using SigProfilerTopography.

Could you please send me your python code for the topography run?
What is the content of txt files under data directory?
How many mutations do you have?
You can send them to my email address botlusaritas [at] health [dot] ucsd [dot] edu

By default SigProfilerTopography requires at least 2K mutations with at least 0.75 average probability to show up results for an SBS mutational signature of interest. If that is the case, we can relax these constraints and enable to plot signature based figures.

Looking forward to your reply.

Best wishes,
Burcak

**Comment by burcakotlu** [comment]
Dear  Juice,

I couldn't get any replies from you.

You can run the method **runAnalyses** with the following parameters
discreet_mode = True
show_all_signatures = True

If it doesn't help you can further run the method **runAnalyses** with the following parameters
discreet_mode = True
show_all_signatures = True
default_cutoff = 0

If you have any questions please let me know.
Best wishes,
Burcak

**Comment by burcakotlu** [comment]
Dear Jurica,

Later, via email, you wrote that the problem occurred when the given sample names were numbers.
This bug has been resolved for SPT version >= 1.0.77. 

Thanks for letting me know.

Best wishes,
Burcak

**Comment by burcakotlu** [comment]
Dear Jurica,

Later, via email, you wrote that the problem occurred when the given sample names were numbers.
This bug has been resolved for SPT version >= 1.0.77.

Thanks for letting me know.

Best wishes,
Burcak
