### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerTopography#3]
Hi,  5  sigprofilerextractor  sbs signatures were input, but only 3 sbs were analyzed. And strand_bias were empty. Is that normal?

**Comment by burcakotlu** [comment]
Dear [shenhaizhongdechanrao](https://github.com/shenhaizhongdechanrao),

Sorry for answering this question late.

SigProfilerTopography tool requires at least 2000 substitutions, 200 doublets, and 1000 indels with an average probability of 0.75 for each signature in discreet mode.
Therefore, if you don’t have that many substitutions for the signatures of interest, you won’t see any resulting figures for them.
However, you can overwrite those parameters.
As follows :
 
        discreet_mode = True
        average_probability = 0.5 # Change as you wish, of course, the higher, the better
        num_of_sbs_required = 500 # Change as you wish, of course, the higher, the more reliable
 
Or you can run in prob_mode with no num_of_sbs_required requirement:
 
        discreet_mode = False
        default_cutoff = 0.5 # Change as you wish, of course, the higher, the better

You can also check path_to_your_output_dir/data/Table_SBS_Signature_Cutoff_NumberofMutations_AverageProbability.txt 
and see what is the overall situation for the signatures, their mutations, and their average probability.
 
Suppose all topography features are shown for a signature (which means the constraints above are satisfied), but the strand asymmetries are missing. In that case, you must check whether you have the files required for replication strand asymmetries and replication timing.

If you have any further questions, please let me know.
 
Best wishes,
Burcak

**Comment by shenhaizhongdechanrao** [comment]
Thanks, I will try it.
