### ISSUE TITLE
I couldn’t get the replication strand bias result.

### ISSUE THREAD

**Issue by xown1048** [AlexandrovLab/SigProfilerTopography#7]
Dear developers,

Thank you for the really nice tool.

I couldn’t get the replication strand bias result.

I tried to run my own data and example data to validate whether I can get the replication strand bias result.

I couldn’t get the result in both cases.

I just follow the example running code.

Lagging_real_count and Leading_real_count were 0.

I also installed 
topography.install_nucleosome('GRCh37')
topography.install_atac_seq('GRCh37’)
topography.install_repli_seq('GRCh37') data.

python version = 3.8.7
SigProfilerTopography version = 1.0.87

I also tired it with num_of_sbs_required = 100.

Every results except for replication strand bias was obtained well.

Could you provide a solution? Is there any reason for it?
![image](https://github.com/AlexandrovLab/SigProfilerTopography/assets/90672075/65eefc9e-4581-43c4-96cc-201a1df60b8a)

**Comment by burcakotlu** [comment]
Dear xown1048,

Thank you very much for using SPT.
May I get the script you have used to run SPT and your log files?
You can send them to my email at botlusaritas@health.ucsd.edu

Best wishes,
Burcak

**Comment by xown1048** [comment]
Dear Burcak,

I really appreciate your fast response and help!

I sent an email with the script and log files after the weekend just in case.

I just followed the github tutorial as much as I could. 

If you have a request or question, please let me know.

Best,
Taejoo

**Comment by burcakotlu** [comment]
Dear Taejoo,

Could you please resend me your script and log files?
Since I couldn't receive any email from you.
Please send your files to **botlusaritas@health.ucsd.edu**  and **burcako@metu.edu.tr**

Best,
Burcak

**Comment by xown1048** [comment]
Dear Burcak,

I really appreciate your help!

It's been fixed well after upgrading the tool (the latest version of SPT 1.0.89) as you suggested.

Sincerely thank you.

Thank you so much for developing a really useful and good tool and solving the issue.

Best,
Taejoo
![SBS40_circle_bar_plots](https://github.com/AlexandrovLab/SigProfilerTopography/assets/90672075/e9e6cf58-8c96-41ca-a9a6-f211edd1a544)

**Comment by burcakotlu** [comment]
I'm happy that your issue is resolved.
With this, I will close this issue.
If you have any further questions, please let me know.
Best wishes,
Burcak
